# Jekyll Configuration for Veridian Zenith
# Where things are
source              : .
destination         : _site
collections_dir     : .
plugins_dir         : _plugins
layouts_dir         : _layouts
includes_dir        : _includes
data_dir            : _data
sass:
  style: compressed

# Handling Reading
safe                 : false
include              : [".htaccess"]
exclude              : ["node_modules", ".github", "vendor"]
keep_files           : [".git", ".svn", "vendor"]
encoding             : "utf-8"
markdown_ext         : "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts          : null
limit_posts          : 0
future               : false
unpublished          : false

# Plugins
whitelist            : []
gems                 : []

# Conversion
highlighter          : rouge
markdown             : kramdown
kramdown:
  auto_ids           : true
  footnote_nr        : 1
  entity_output      : as_char
  toc_levels         : 1..6
  smart_quotes       : lsquo,rsquo,ldquo,rdquo
  enable_coderay     : false

# Serving
detach               : false
port                 : 4000
host                 : 127.0.0.1
baseurl              : ""
url                  : "https://veridianzenith.qzz.io"

# Building
verbose              : false
quiet                : false
show_page_names      : false

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
